### ISSUE TITLE
Roadmap for OGGM v1.6

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#1407]
Here are the things I'd like to get done before v1.6 (hopefully in a couple of months):

- [ ] Velocities from Millan et al in the shop: https://github.com/OGGM/oggm/issues/1401
- [ ] Possible bug in preprocessing: https://github.com/OGGM/oggm/issues/1360 
- [ ] Better filter output: https://github.com/OGGM/oggm/issues/1359 
- [ ] New default preprocessed directories calibrated on a glacier per glacier basis
- [ ] Simplification of the tutorials and focus on operational runs using the new glacier directories

**Comment by nchampollion** [comment]
I wonder when you want to do this release ? And you wish to do a bigger release like Version 2.0 by including debris-cover module and other surface mass balance module ? And also the new way to initialize the model ?

**Comment by fmaussion** [comment]
Not really a 2.0 but 1.6. Yes my goal would be that the default glacier directories use the new spinup from @pat-schmitt and the correction to the calibration that @lilianschuster made (mostly: getting away from hydrological years)

**Comment by fmaussion** [comment]
(but keep in mind that only the defaults will change - as far as possible we try to keep all options still open and usable in OGGM)
