### ISSUE TITLE
TODOs for Global ITMIX

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#426]
OGGM will participate to the [Global Glacier Thickness Initiative](http://people.ee.ethz.ch/%7Edanielfa/IACS/G2TI.html). We are a bit late on the deadline (like always) and we won't be able to make the "best" contribution according to the general OGGM goals, but here is the list of things I'd like to get in before that:
- [x] Implement Cuffey and Patterson's shape factors to the flowline model: https://github.com/OGGM/oggm/issues/423
- [x] Implement a better interpolation algorithm for distributed bed maps: https://github.com/OGGM/oggm/issues/424
- [ ] Run OGGM with a revised RGI based on the partitioning algorithm: https://github.com/OGGM/oggm/issues/425

**Comment by fmaussion** [comment]
#425 is bigger than expected, and global ITMIX is now over ;-)
