### ISSUE TITLE
Roadmap for easier/faster deploy

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm#68]
I find working with AWS already very pleasant and above all: fast!

I still have a couple of ideas to make the experience a bit easier, comments/additions/pull requests welcome!
- [x] git: configfile (https://github.com/OGGM/oggm/issues/67)
- [x] new option to pin the exact region? (https://github.com/OGGM/oggm/issues/51)
- [ ] improve data download (this is a larger undertaking, https://github.com/OGGM/oggm/issues/58)
- [ ] other tools to make life easier? I don't know if this is reasonable or possible, but common actions between local and AWS machine include: rsync, scp, developing and running code. Could some of these be simplified with fabric commands? I will also look into pycharm on AWS (e.g. [here](https://plugins.jetbrains.com/plugin/4558?pr=idea) to see if this can work, but I m not sure)

@TimoRoth , @fso42 , @bmarzeion nothing very urgent here but if you have any thoughts/comments, please do so!
